# C6 - NumPy Array Broadcasting

**Limitation:** Arithmetic, including broadcasting, can only be performed when the shape of each dimention in the arrays are equal or one has the dimention size of 1.

In [2]:
# Broadcast scalar to one-dimentional array

from numpy import array

a = array([1, 2, 3])
b = 2

# Broadcast
c = a + b
print(c) # [3, 4, 5]

[3 4 5]


In [3]:
# Broadcast scalar to two-dimentional array

from numpy import array

A = array([
    [1, 2, 3],
    [1, 2, 3]
])
b = 2

# Broadcast
C = A + b
print(C) # [[3 4 5]
         #  [3 4 5]]

[[3 4 5]
 [3 4 5]]


In [4]:
# Broadcast one-dimentional array to two-dimentional array

from numpy import array

A = array([
    [1, 2, 3],
    [1, 2, 3]
])
b = array([1, 2, 3])

# Broadcast
C = A + b
print(C) # [[2 4 6]
         #  [2 4 6]]

[[2 4 6]
 [2 4 6]]


In [6]:
# Fail to broadcast

from numpy import array

A = array([
    [1, 2, 3],
    [1, 2, 3]
])
b = array([1, 2])

# Broadcast
C = A + b
print(C) # ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 