## A sparse matrix is a matrix that is comprised of mostly zero values.

In [7]:
# Sparse matrix
from numpy import array
from numpy import count_nonzero
from scipy.sparse import csr_matrix # compressed sparse row

A = array([
    [1, 0, 0, 1, 0, 0],
    [0, 2, 0, 1, 0, 1],
    [0, 0, 0, 2, 0, 0]
])

# Calculate sparsity
sparsity = 1.0 - count_nonzero(A) / A.size
print(sparsity) # 0.6666666666666667

# Convert to sparse matrix (CSR method)
S = csr_matrix(A)
print(S)  # (0, 0)	1
          # (0, 3)	1
          # (1, 1)	2
          # (1, 3)	1
          # (1, 5)	1
          # (2, 3)	2
# reconstruct dense matrix
B = S.todense()
print(B) # [[1 0 0 1 0 0]
         #  [0 2 0 1 0 1]
         #  [0 0 0 2 0 0]]

0.6666666666666667
  (0, 0)	1
  (0, 3)	1
  (1, 1)	2
  (1, 3)	1
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 2 0 1 0 1]
 [0 0 0 2 0 0]]
